spring:
  application:
    name: spring-babel-rag
  config:
    import: optional:file:.env[.properties]

blog-write-agent:
  outputDir: blog-posts

embabel:
  agent:
    platform:
      models:
        openai:
          api-key: ${OPENAI_API_KEY}
      toolloop:
        max-iteration: 8
  models:
    default-llm: gpt-5-mini
    llms:
      editor: gpt-4o
      reviewer: gpt-5-mini